### ISSUE TITLE
Build for 7.5.0

### ISSUE THREAD

**Issue by nelg** [johtani/elasticsearch-ingest-csv#10]
I don't seem to be able to build for 7.5.0.  Any thoughts on what needs changing to make it work?

**Comment by johtani** [comment]
Unfortunately, there is a bug in 7.5.0. https://github.com/elastic/elasticsearch/issues/49787

**Comment by johtani** [comment]
But there is a workaround. I'll try it.
https://github.com/elastic/elasticsearch/issues/49787#issuecomment-562704640

**Comment by johtani** [comment]
@nelg Released 7.5.0 on GitHub with #8 . Thanks for great PR!
