### ISSUE TITLE
why not version 6.8.4

### ISSUE THREAD

**Issue by zhuermu** [johtani/elasticsearch-ingest-csv#7]
why not version 6.8.4

**Comment by nelg** [comment]
extremely likely we just didn't get around to building that version. 
I've built you a release for 6.8.4, at:
https://github.com/nelg/elasticsearch-ingest-csv/releases

I have not tested it, as I'm not using that version, but it should work.
You can see the compile at:
https://github.com/nelg/elasticsearch-ingest-csv/commit/e27289bdcf5080d3ae6132c98722797e9b0b6b37/checks?check_suite_id=336946780

**Comment by johtani** [comment]
Hi @zhuermu 

Thanks for raising this issue.

I've released `6.8.4` and `6.8.5` to sonatype repository.
See https://github.com/johtani/elasticsearch-ingest-csv/tree/6.x

**Comment by zhuermu** [comment]
.8.4.jar:6.8.4]\n","stream":"stdout","time":"2019-12-18T13:54:15.87239063Z"}
{"log":"Caused by: java.lang.IllegalStateException: failed to load plugin ingest-csv due to jar hell\n","stream":"stdout","time":"2019-12-18T13:54:15.872394254Z"}

There are some problem，when I down 6.8.4.0
